#!/usr/bin/env bash
# build-souls.sh — Builds fully-resolved SOUL.md for each fleet agent
# Base content from SOUL.base.md with real values substituted — no placeholders at runtime
# Usage: bash scripts/build-souls.sh

set -euo pipefail

ORG="f86d92cb-db10-43ff-9ff2-d69c319d272d"
BASE="$(dirname "$0")/../instances/SOUL.base.md"
INSTANCES="$(dirname "$0")/../instances"

build() {
  local slug=$1 agent_id=$2 name=$3 role=$4
  local out="$INSTANCES/$slug/SOUL.md"
  mkdir -p "$INSTANCES/$slug"

  cat > "$out" << HEADER
# ${name} — SOUL.md
# Auto-generated by build-souls.sh — do not edit directly
# Edit SOUL.base.md or instances/${slug}/routing.md then re-run build-souls.sh

## Agent Identity
- **Name:** ${name}
- **ID:** \`${agent_id}\`
- **Role:** ${role}
- **Org ID:** \`${ORG}\`

HEADER

  case $slug in
    sales) cat >> "$out" << 'R'
## Routing — When to hand off
- Technical/support questions → Fleet-Support (`325e5143-3c0b-4d65-b548-a34cbdba5949`)
- Engineering/dev questions → Fleet-Dev (`87a2838e-e145-4f5c-99e2-c759f0591cba`)
- IT/infrastructure → Fleet-IT (`20dc090b-90a3-403f-acc3-a1ac7008596d`)
- Escalations, admin → Fleet-Manager (`82061d1c-2c79-4cfb-9e18-b8223b95a7c2`)

R
    ;;
    support) cat >> "$out" << 'R'
## Routing — When to hand off
- Sales/commercial questions → Fleet-Sales (`b81c0d8a-3f76-43fe-b2e5-2537801085dc`)
- Engineering/dev questions → Fleet-Dev (`87a2838e-e145-4f5c-99e2-c759f0591cba`)
- IT/infrastructure → Fleet-IT (`20dc090b-90a3-403f-acc3-a1ac7008596d`)
- Escalations, admin → Fleet-Manager (`82061d1c-2c79-4cfb-9e18-b8223b95a7c2`)

R
    ;;
    manager) cat >> "$out" << 'R'
## Routing — When to hand off
- Sales tasks → Fleet-Sales (`b81c0d8a-3f76-43fe-b2e5-2537801085dc`)
- Support tasks → Fleet-Support (`325e5143-3c0b-4d65-b548-a34cbdba5949`)
- Dev tasks → Fleet-Dev (`87a2838e-e145-4f5c-99e2-c759f0591cba`)
- IT tasks → Fleet-IT (`20dc090b-90a3-403f-acc3-a1ac7008596d`)
- Manager has org-wide visibility — can list ALL handoffs across all agents

R
    ;;
    dev) cat >> "$out" << 'R'
## Routing — When to hand off
- Sales/commercial → Fleet-Sales (`b81c0d8a-3f76-43fe-b2e5-2537801085dc`)
- Support/user issues → Fleet-Support (`325e5143-3c0b-4d65-b548-a34cbdba5949`)
- IT/infra/access → Fleet-IT (`20dc090b-90a3-403f-acc3-a1ac7008596d`)
- Escalations → Fleet-Manager (`82061d1c-2c79-4cfb-9e18-b8223b95a7c2`)

R
    ;;
    it) cat >> "$out" << 'R'
## Routing — When to hand off
- Sales/commercial → Fleet-Sales (`b81c0d8a-3f76-43fe-b2e5-2537801085dc`)
- Dev/engineering → Fleet-Dev (`87a2838e-e145-4f5c-99e2-c759f0591cba`)
- Support/user issues → Fleet-Support (`325e5143-3c0b-4d65-b548-a34cbdba5949`)
- Escalations → Fleet-Manager (`82061d1c-2c79-4cfb-9e18-b8223b95a7c2`)

R
    ;;
  esac

  # Append fully-resolved base (sed substitutes all placeholders)
  sed \
    -e "s|{{AGENT_ID}}|${agent_id}|g" \
    -e "s|{{AGENT_NAME}}|${name}|g" \
    -e "s|{{ORG_ID}}|${ORG}|g" \
    "$BASE" >> "$out"

  echo "  built: $slug"
}

echo "==> Building resolved SOUL.md files..."
build sales   "b81c0d8a-3f76-43fe-b2e5-2537801085dc" "Fleet-Sales"   "Sales — lead qualification, proposals, pricing, CRM, HubSpot"
build support "325e5143-3c0b-4d65-b548-a34cbdba5949" "Fleet-Support" "Support — onboarding, troubleshooting, user issues, SLA"
build manager "82061d1c-2c79-4cfb-9e18-b8223b95a7c2" "Fleet-Manager" "Manager — org-wide visibility, escalations, admin, reports"
build dev     "87a2838e-e145-4f5c-99e2-c759f0591cba" "Fleet-Dev"     "Dev — software engineering, GitHub, SDLC, infra, architecture"
build it      "20dc090b-90a3-403f-acc3-a1ac7008596d" "Fleet-IT"      "IT — security, access control, hardware, compliance, system admin"

echo ""
echo "==> Deploying to live instance workspaces..."
SCRIPT_DIR="$(dirname "$0")"
cp "$INSTANCES/sales/SOUL.md"   "$HOME/cbfleet-rag-sales/.openclaw/workspace/SOUL.md"   && echo "  deployed: sales"
cp "$INSTANCES/support/SOUL.md" "$HOME/cbfleet-rag-support/.openclaw/workspace/SOUL.md" && echo "  deployed: support"
cp "$INSTANCES/manager/SOUL.md" "$HOME/cbfleet-rag-manager/.openclaw/workspace/SOUL.md" && echo "  deployed: manager"
cp "$INSTANCES/dev/SOUL.md"     "$HOME/cbfleet-rag-dev/.openclaw/workspace/SOUL.md"     && echo "  deployed: dev"
cp "$INSTANCES/it/SOUL.md"      "$HOME/cbfleet-rag-it/.openclaw/workspace/SOUL.md"      && echo "  deployed: it"

echo ""
echo "==> Done. All 5 SOUL.md files built and deployed."
echo "    To add a new agent: add a build() call above + routing block, then re-run."
